# Generated by Django 5.1.5 on 2025-01-22 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchcenter',
            name='numbering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mydash.numbering'),
        ),
    ]
