# Generated by Django 5.1.5 on 2025-02-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydash', '0004_alter_timerange_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
